apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidfort-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-details-app
  template:
    metadata:
      labels:
        app: file-details-app
    spec:
      containers:
      - name: file-details-container
        image: abhishek11724/rapidfort_api:latest
        ports:
        - containerPort: 80