apiVersion: v1
kind: Service
metadata:
  name: rapidfort-api-service
spec:
  selector:
    app: file-details-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer